
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class AbilityTree : Luban.BeanBase
{
    public AbilityTree(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        StartAbilityId = _buf.GetProperty("start_ability_id").GetInt32();
        { var __json0 = _buf.GetProperty("middle_ability_ids"); MiddleAbilityIds = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  MiddleAbilityIds.Add(__v0); }   }
        EndAbilityId = _buf.GetProperty("end_ability_id").GetInt32();
    }

    public static AbilityTree DeserializeAbilityTree(JsonElement _buf)
    {
        return new AbilityTree(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 开始技能
    /// </summary>
    public readonly int StartAbilityId;
    /// <summary>
    /// 中间技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> MiddleAbilityIds;
    /// <summary>
    /// 结尾技能
    /// </summary>
    public readonly int EndAbilityId;
   
    public const int __ID__ = 1953537992;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "startAbilityId:" + StartAbilityId + ","
        + "middleAbilityIds:" + Luban.StringUtil.CollectionToString(MiddleAbilityIds) + ","
        + "endAbilityId:" + EndAbilityId + ","
        + "}";
    }
}

}
