
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Ability : Luban.BeanBase
{
    public Ability(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        { var __json0 = _buf.GetProperty("values"); Values = new System.Collections.Generic.List<float>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { float __v0;  __v0 = __e0.GetSingle();  Values.Add(__v0); }   }
        ClassName = _buf.GetProperty("class_name").GetString();
        { var __json0 = _buf.GetProperty("clash_abilities"); ClashAbilities = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  ClashAbilities.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("next_abilities"); NextAbilities = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  NextAbilities.Add(__v0); }   }
    }

    public static Ability DeserializeAbility(JsonElement _buf)
    {
        return new Ability(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly System.Collections.Generic.List<float> Values;
    /// <summary>
    /// 类名（也是图标名）
    /// </summary>
    public readonly string ClassName;
    /// <summary>
    /// 互斥升级
    /// </summary>
    public readonly System.Collections.Generic.List<int> ClashAbilities;
    /// <summary>
    /// 下一级升级
    /// </summary>
    public readonly System.Collections.Generic.List<int> NextAbilities;
   
    public const int __ID__ = 464145674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "values:" + Luban.StringUtil.CollectionToString(Values) + ","
        + "className:" + ClassName + ","
        + "clashAbilities:" + Luban.StringUtil.CollectionToString(ClashAbilities) + ","
        + "nextAbilities:" + Luban.StringUtil.CollectionToString(NextAbilities) + ","
        + "}";
    }
}

}
