
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class BossMobInfo : Luban.BeanBase
{
    public BossMobInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        SceneName = _buf.GetProperty("scene_name").GetString();
        Health = _buf.GetProperty("health").GetSingle();
        Speed = _buf.GetProperty("speed").GetSingle();
        Damage = _buf.GetProperty("damage").GetSingle();
        Targeting = _buf.GetProperty("targeting").GetSingle();
        ShootCd = _buf.GetProperty("shoot_cd").GetSingle();
    }

    public static BossMobInfo DeserializeBossMobInfo(JsonElement _buf)
    {
        return new BossMobInfo(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 场景名
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly float Health;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 转向速度
    /// </summary>
    public readonly float Targeting;
    /// <summary>
    /// 攻击CD
    /// </summary>
    public readonly float ShootCd;
   
    public const int __ID__ = 1071955841;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "sceneName:" + SceneName + ","
        + "health:" + Health + ","
        + "speed:" + Speed + ","
        + "damage:" + Damage + ","
        + "targeting:" + Targeting + ","
        + "shootCd:" + ShootCd + ","
        + "}";
    }
}

}
