
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Buff : Luban.BeanBase
{
    public Buff(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        { var __json0 = _buf.GetProperty("values"); Values = new System.Collections.Generic.List<float>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { float __v0;  __v0 = __e0.GetSingle();  Values.Add(__v0); }   }
        Duration = _buf.GetProperty("duration").GetSingle();
        RepeatTime = _buf.GetProperty("repeat_time").GetSingle();
        ClassName = _buf.GetProperty("class_name").GetString();
    }

    public static Buff DeserializeBuff(JsonElement _buf)
    {
        return new Buff(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly System.Collections.Generic.List<float> Values;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 循环时间
    /// </summary>
    public readonly float RepeatTime;
    /// <summary>
    /// 类名
    /// </summary>
    public readonly string ClassName;
   
    public const int __ID__ = 2081907;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "values:" + Luban.StringUtil.CollectionToString(Values) + ","
        + "duration:" + Duration + ","
        + "repeatTime:" + RepeatTime + ","
        + "className:" + ClassName + ","
        + "}";
    }
}

}
