
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Constants : Luban.BeanBase
{
    public Constants(JsonElement _buf) 
    {
        BurstInterval = _buf.GetProperty("burst_interval").GetSingle();
        PlayerHealth = _buf.GetProperty("player_health").GetSingle();
        PlayerSpeed = _buf.GetProperty("player_speed").GetSingle();
        PlayerDamage = _buf.GetProperty("player_damage").GetSingle();
        PlayerShootSpeed = _buf.GetProperty("player_shoot_speed").GetSingle();
        PlayerBulletSpeed = _buf.GetProperty("player_bullet_speed").GetSingle();
        PlayerShootSpread = _buf.GetProperty("player_shoot_spread").GetSingle();
        PlayerKnockBack = _buf.GetProperty("player_knock_back").GetSingle();
        PlayerBurstFire = _buf.GetProperty("player_burst_fire").GetSingle();
        PlayerBulletSize = _buf.GetProperty("player_bullet_size").GetSingle();
        PlayerBulletDegeneration = _buf.GetProperty("player_bullet_degeneration").GetSingle();
        PlayerRecoil = _buf.GetProperty("player_recoil").GetSingle();
        PlayerBulletCount = _buf.GetProperty("player_bullet_count").GetSingle();
        PlayerBlastDamage = _buf.GetProperty("player_blast_damage").GetSingle();
        PlayerBlastRadius = _buf.GetProperty("player_blast_radius").GetSingle();
        MaxLevel = _buf.GetProperty("max_level").GetSingle();
        MaxMobCount = _buf.GetProperty("max_mob_count").GetInt32();
    }

    public static Constants DeserializeConstants(JsonElement _buf)
    {
        return new Constants(_buf);
    }

    /// <summary>
    /// 默认连发间隔
    /// </summary>
    public readonly float BurstInterval;
    /// <summary>
    /// 默认玩家生命
    /// </summary>
    public readonly float PlayerHealth;
    /// <summary>
    /// 默认玩家速度
    /// </summary>
    public readonly float PlayerSpeed;
    /// <summary>
    /// 默认玩家伤害
    /// </summary>
    public readonly float PlayerDamage;
    /// <summary>
    /// 默认玩家射击速度
    /// </summary>
    public readonly float PlayerShootSpeed;
    /// <summary>
    /// 默认玩家子弹速度
    /// </summary>
    public readonly float PlayerBulletSpeed;
    /// <summary>
    /// 默认玩家武器散布
    /// </summary>
    public readonly float PlayerShootSpread;
    /// <summary>
    /// 默认玩家打中后对目标的击退
    /// </summary>
    public readonly float PlayerKnockBack;
    /// <summary>
    /// 默认玩家BurstFire
    /// </summary>
    public readonly float PlayerBurstFire;
    /// <summary>
    /// 默认玩家子弹大小
    /// </summary>
    public readonly float PlayerBulletSize;
    /// <summary>
    /// 默认玩家子弹退化速度
    /// </summary>
    public readonly float PlayerBulletDegeneration;
    /// <summary>
    /// 默认射击后坐力
    /// </summary>
    public readonly float PlayerRecoil;
    /// <summary>
    /// 默认子弹数量
    /// </summary>
    public readonly float PlayerBulletCount;
    /// <summary>
    /// 默认爆炸伤害
    /// </summary>
    public readonly float PlayerBlastDamage;
    /// <summary>
    /// 默认爆炸半径
    /// </summary>
    public readonly float PlayerBlastRadius;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly float MaxLevel;
    /// <summary>
    /// 最大同屏怪物数量
    /// </summary>
    public readonly int MaxMobCount;
   
    public const int __ID__ = 1581691183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "burstInterval:" + BurstInterval + ","
        + "playerHealth:" + PlayerHealth + ","
        + "playerSpeed:" + PlayerSpeed + ","
        + "playerDamage:" + PlayerDamage + ","
        + "playerShootSpeed:" + PlayerShootSpeed + ","
        + "playerBulletSpeed:" + PlayerBulletSpeed + ","
        + "playerShootSpread:" + PlayerShootSpread + ","
        + "playerKnockBack:" + PlayerKnockBack + ","
        + "playerBurstFire:" + PlayerBurstFire + ","
        + "playerBulletSize:" + PlayerBulletSize + ","
        + "playerBulletDegeneration:" + PlayerBulletDegeneration + ","
        + "playerRecoil:" + PlayerRecoil + ","
        + "playerBulletCount:" + PlayerBulletCount + ","
        + "playerBlastDamage:" + PlayerBlastDamage + ","
        + "playerBlastRadius:" + PlayerBlastRadius + ","
        + "maxLevel:" + MaxLevel + ","
        + "maxMobCount:" + MaxMobCount + ","
        + "}";
    }
}

}
