
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Constants : Luban.BeanBase
{
    public Constants(JsonElement _buf) 
    {
        KnockBackShootDistance = _buf.GetProperty("knock_back_shoot_distance").GetSingle();
        KnockBackOnhitDistance = _buf.GetProperty("knock_back_onhit_distance").GetSingle();
    }

    public static Constants DeserializeConstants(JsonElement _buf)
    {
        return new Constants(_buf);
    }

    /// <summary>
    /// 默认射击后坐力
    /// </summary>
    public readonly float KnockBackShootDistance;
    /// <summary>
    /// 默认被打后坐力
    /// </summary>
    public readonly float KnockBackOnhitDistance;
   
    public const int __ID__ = 1581691183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "knockBackShootDistance:" + KnockBackShootDistance + ","
        + "knockBackOnhitDistance:" + KnockBackOnhitDistance + ","
        + "}";
    }
}

}
