
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbEffects
{
    private readonly System.Collections.Generic.Dictionary<int, Effects> _dataMap;
    private readonly System.Collections.Generic.List<Effects> _dataList;
    
    public TbEffects(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Effects>();
        _dataList = new System.Collections.Generic.List<Effects>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Effects _v;
            _v = Effects.DeserializeEffects(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Effects> DataMap => _dataMap;
    public System.Collections.Generic.List<Effects> DataList => _dataList;

    public Effects GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Effects Get(int key) => _dataMap[key];
    public Effects this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

