
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbWeapon
{
    private readonly System.Collections.Generic.Dictionary<int, Weapon> _dataMap;
    private readonly System.Collections.Generic.List<Weapon> _dataList;
    
    public TbWeapon(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Weapon>();
        _dataList = new System.Collections.Generic.List<Weapon>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Weapon _v;
            _v = Weapon.DeserializeWeapon(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Weapon> DataMap => _dataMap;
    public System.Collections.Generic.List<Weapon> DataList => _dataList;

    public Weapon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Weapon Get(int key) => _dataMap[key];
    public Weapon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

