
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbStoreInfo
{
    private readonly System.Collections.Generic.Dictionary<int, StoreInfo> _dataMap;
    private readonly System.Collections.Generic.List<StoreInfo> _dataList;
    
    public TbStoreInfo(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StoreInfo>();
        _dataList = new System.Collections.Generic.List<StoreInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            StoreInfo _v;
            _v = StoreInfo.DeserializeStoreInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StoreInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<StoreInfo> DataList => _dataList;

    public StoreInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StoreInfo Get(int key) => _dataMap[key];
    public StoreInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

