
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.DataBase
{ 
    public enum GoodsType
    {
        /// <summary>
        /// 升级
        /// </summary>
        Upgrade = 0,
        /// <summary>
        /// UI
        /// </summary>
        UiSkin = 1,
        /// <summary>
        /// 死亡动画
        /// </summary>
        DieAnimation = 2,
        /// <summary>
        /// 出生动画
        /// </summary>
        SpawnAnimation = 3,
        /// <summary>
        /// 武器皮肤
        /// </summary>
        WeaponSkin = 4,
        /// <summary>
        /// 飞船皮肤
        /// </summary>
        BodySkin = 5,
        /// <summary>
        /// 护盾皮肤
        /// </summary>
        ShieldSkin = 6,
    }

} 

