
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbPowertUpInfo
{
    private readonly System.Collections.Generic.Dictionary<int, PowerUpInfo> _dataMap;
    private readonly System.Collections.Generic.List<PowerUpInfo> _dataList;
    
    public TbPowertUpInfo(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PowerUpInfo>();
        _dataList = new System.Collections.Generic.List<PowerUpInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            PowerUpInfo _v;
            _v = PowerUpInfo.DeserializePowerUpInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PowerUpInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<PowerUpInfo> DataList => _dataList;

    public PowerUpInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PowerUpInfo Get(int key) => _dataMap[key];
    public PowerUpInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

