
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbAbilityTree
{
    private readonly System.Collections.Generic.Dictionary<int, AbilityTree> _dataMap;
    private readonly System.Collections.Generic.List<AbilityTree> _dataList;
    
    public TbAbilityTree(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AbilityTree>();
        _dataList = new System.Collections.Generic.List<AbilityTree>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            AbilityTree _v;
            _v = AbilityTree.DeserializeAbilityTree(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AbilityTree> DataMap => _dataMap;
    public System.Collections.Generic.List<AbilityTree> DataList => _dataList;

    public AbilityTree GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AbilityTree Get(int key) => _dataMap[key];
    public AbilityTree this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

