
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbAbility
{
    private readonly System.Collections.Generic.Dictionary<int, Ability> _dataMap;
    private readonly System.Collections.Generic.List<Ability> _dataList;
    
    public TbAbility(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Ability>();
        _dataList = new System.Collections.Generic.List<Ability>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Ability _v;
            _v = Ability.DeserializeAbility(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Ability> DataMap => _dataMap;
    public System.Collections.Generic.List<Ability> DataList => _dataList;

    public Ability GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Ability Get(int key) => _dataMap[key];
    public Ability this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

