
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbDroneInfo
{
    private readonly System.Collections.Generic.Dictionary<int, DroneInfo> _dataMap;
    private readonly System.Collections.Generic.List<DroneInfo> _dataList;
    
    public TbDroneInfo(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DroneInfo>();
        _dataList = new System.Collections.Generic.List<DroneInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            DroneInfo _v;
            _v = DroneInfo.DeserializeDroneInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DroneInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<DroneInfo> DataList => _dataList;

    public DroneInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DroneInfo Get(int key) => _dataMap[key];
    public DroneInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

