
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbMobInfo
{
    private readonly System.Collections.Generic.Dictionary<int, MobInfo> _dataMap;
    private readonly System.Collections.Generic.List<MobInfo> _dataList;
    
    public TbMobInfo(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MobInfo>();
        _dataList = new System.Collections.Generic.List<MobInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            MobInfo _v;
            _v = MobInfo.DeserializeMobInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MobInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<MobInfo> DataList => _dataList;

    public MobInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MobInfo Get(int key) => _dataMap[key];
    public MobInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

