
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbShield
{
    private readonly System.Collections.Generic.Dictionary<int, Shield> _dataMap;
    private readonly System.Collections.Generic.List<Shield> _dataList;
    
    public TbShield(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Shield>();
        _dataList = new System.Collections.Generic.List<Shield>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Shield _v;
            _v = Shield.DeserializeShield(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Shield> DataMap => _dataMap;
    public System.Collections.Generic.List<Shield> DataList => _dataList;

    public Shield GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Shield Get(int key) => _dataMap[key];
    public Shield this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

