
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbBossMobInfo
{
    private readonly System.Collections.Generic.Dictionary<int, BossMobInfo> _dataMap;
    private readonly System.Collections.Generic.List<BossMobInfo> _dataList;
    
    public TbBossMobInfo(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BossMobInfo>();
        _dataList = new System.Collections.Generic.List<BossMobInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            BossMobInfo _v;
            _v = BossMobInfo.DeserializeBossMobInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BossMobInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<BossMobInfo> DataList => _dataList;

    public BossMobInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BossMobInfo Get(int key) => _dataMap[key];
    public BossMobInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

