
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.DataBase
{
public partial class TbPlayerBuild
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerBuild> _dataMap;
    private readonly System.Collections.Generic.List<PlayerBuild> _dataList;
    
    public TbPlayerBuild(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerBuild>();
        _dataList = new System.Collections.Generic.List<PlayerBuild>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            PlayerBuild _v;
            _v = PlayerBuild.DeserializePlayerBuild(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PlayerBuild> DataMap => _dataMap;
    public System.Collections.Generic.List<PlayerBuild> DataList => _dataList;

    public PlayerBuild GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlayerBuild Get(int key) => _dataMap[key];
    public PlayerBuild this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

