
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class DroneInfo : Luban.BeanBase
{
    public DroneInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        SceneName = _buf.GetProperty("scene_name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        Health = _buf.GetProperty("health").GetSingle();
        Speed = _buf.GetProperty("speed").GetSingle();
        Damage = _buf.GetProperty("damage").GetSingle();
        Targeting = _buf.GetProperty("targeting").GetSingle();
        ShootCd = _buf.GetProperty("shoot_cd").GetSingle();
        BulletCount = _buf.GetProperty("bullet_count").GetInt32();
        BulletSpeed = _buf.GetProperty("bullet_speed").GetSingle();
    }

    public static DroneInfo DeserializeDroneInfo(JsonElement _buf)
    {
        return new DroneInfo(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 场景名
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly float Health;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 子弹追踪
    /// </summary>
    public readonly float Targeting;
    /// <summary>
    /// 攻击CD
    /// </summary>
    public readonly float ShootCd;
    /// <summary>
    /// 子弹数量
    /// </summary>
    public readonly int BulletCount;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly float BulletSpeed;
   
    public const int __ID__ = 1437490118;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "sceneName:" + SceneName + ","
        + "desc:" + Desc + ","
        + "health:" + Health + ","
        + "speed:" + Speed + ","
        + "damage:" + Damage + ","
        + "targeting:" + Targeting + ","
        + "shootCd:" + ShootCd + ","
        + "bulletCount:" + BulletCount + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "}";
    }
}

}
