
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class MobInfo : Luban.BeanBase
{
    public MobInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        IconName = _buf.GetProperty("icon_name").GetString();
        Health = _buf.GetProperty("health").GetSingle();
        Speed = _buf.GetProperty("speed").GetSingle();
        Damage = _buf.GetProperty("damage").GetSingle();
    }

    public static MobInfo DeserializeMobInfo(JsonElement _buf)
    {
        return new MobInfo(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标名
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly float Health;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
   
    public const int __ID__ = -1406036050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "iconName:" + IconName + ","
        + "health:" + Health + ","
        + "speed:" + Speed + ","
        + "damage:" + Damage + ","
        + "}";
    }
}

}
