
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class PlayerBuild : Luban.BeanBase
{
    public PlayerBuild(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        { var __json0 = _buf.GetProperty("abilities"); Abilities = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Abilities.Add(__v0); }   }
        ShooterId = _buf.GetProperty("shooter_id").GetInt32();
        BodyId = _buf.GetProperty("body_id").GetInt32();
        ShieldId = _buf.GetProperty("shield_id").GetInt32();
    }

    public static PlayerBuild DeserializePlayerBuild(JsonElement _buf)
    {
        return new PlayerBuild(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 能力ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> Abilities;
    /// <summary>
    /// 武器ID
    /// </summary>
    public readonly int ShooterId;
    /// <summary>
    /// 身体ID
    /// </summary>
    public readonly int BodyId;
    /// <summary>
    /// 盾牌ID
    /// </summary>
    public readonly int ShieldId;
   
    public const int __ID__ = -2096723987;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "abilities:" + Luban.StringUtil.CollectionToString(Abilities) + ","
        + "shooterId:" + ShooterId + ","
        + "bodyId:" + BodyId + ","
        + "shieldId:" + ShieldId + ","
        + "}";
    }
}

}
