
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class StoreInfo : Luban.BeanBase
{
    public StoreInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        Type = (DataBase.GoodsType)_buf.GetProperty("type").GetInt32();
        Price = _buf.GetProperty("price").GetInt32();
        Value = _buf.GetProperty("value").GetInt32();
        IconName = _buf.GetProperty("icon_name").GetString();
    }

    public static StoreInfo DeserializeStoreInfo(JsonElement _buf)
    {
        return new StoreInfo(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly DataBase.GoodsType Type;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 值
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 图标名
    /// </summary>
    public readonly string IconName;
   
    public const int __ID__ = -599353073;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "price:" + Price + ","
        + "value:" + Value + ","
        + "iconName:" + IconName + ","
        + "}";
    }
}

}
