
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;

namespace cfg
{
public partial class Tables
{
    public DataBase.TbAbility TbAbility {get; }

    public Tables(System.Func<string, JsonElement> loader)
    {
        TbAbility = new DataBase.TbAbility(loader("database_tbability"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAbility.ResolveRef(this);
    }
}

}
