
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        SceneName = _buf.GetProperty("scene_name").GetString();
        ShootSpeed = _buf.GetProperty("shoot_speed").GetSingle();
        BulletSpeed = _buf.GetProperty("bullet_speed").GetSingle();
        ShootSpread = _buf.GetProperty("shoot_spread").GetSingle();
    }

    public static Weapon DeserializeWeapon(JsonElement _buf)
    {
        return new Weapon(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 场景名
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// 射击CD
    /// </summary>
    public readonly float ShootSpeed;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 武器散射
    /// </summary>
    public readonly float ShootSpread;
   
    public const int __ID__ = -1707954628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "sceneName:" + SceneName + ","
        + "shootSpeed:" + ShootSpeed + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "shootSpread:" + ShootSpread + ","
        + "}";
    }
}

}
